# Site settings
title: Ops Trouble Shooting
email: admin@opsts.com
description: > # this means to ignore newlines until "baseurl:"
  此处将记载运维各种经验，以及一些黑魔法，有兴趣撰文的欢迎PR
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://opsts.com" # the base hostname & protocol for your site
#twitter_username: opsts
github_username:  opsts

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# Disqus settings
disqus_username: opsts
